# Generated by Django 4.1.2 on 2022-10-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TO_DO_LIST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='data',
            field=models.CharField(max_length=10),
        ),
    ]
